steps:
  - name: hashicorp/terraform:1.9
    id: terraform-apply
    entrypoint: sh
    args:
      - -c
      - |
        terraform init
        terraform apply --auto-approve

options:
  logging: CLOUD_LOGGING_ONLY
